apiVersion: v1
kind: Namespace
metadata:
  name: pod-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-a
  namespace: pod-test
spec:
  replicas: 20
  selector:
    matchLabels:
      app: pod-a
  template:
    metadata:
      labels:
        app: pod-a
    spec:
      #schedulerName: chronos
      containers:
        - name: pod-a
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              apt-get update && apt-get install -y iputils-ping gawk > /dev/null
              ping -c 20 pod-b.pod-test.svc.cluster.local | tee /tmp/ping.out
              awk -F'/' '/rtt/ { printf("Average latency: %s ms\n", $5) }' /tmp/ping.out
              while true; do ping -c 5 pod-b.pod-test.svc.cluster.local; sleep 1; done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-b
  namespace: pod-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-b
  template:
    metadata:
      labels:
        app: pod-b
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - c-alpha
      containers:
        - name: busybox
          image: busybox
          command:
            - sh
            - -c
            - while true; do ping -c 5 pod-a.pod-test.svc.cluster.local; sleep 1; done